#!/usr/bin/env python3

'''
editfastqheaders.py

This code edits fastq headers from RNA-seq.
It will take the following header:
@A00127:195:H523HDSXY:1:1101:13738:1360 1:N:0:GAATTCGT+ATAGAGGC
And edit it down to:
A00127:195:H523HDSXY:1:1101:13738:1360

This is not super useful, but I'm saving it nonetheless. 
'''

import sys

def find_between(s, first, last ):
    try:
        start = s.rindex( first ) + len( first )
        end = s.rindex( last, start )
        return s[start:end]
    except ValueError:
        return ""

def editheader(inputfastq, outputfastq):
    with open(inputfastq, 'r') as fh:
        for line in fh:
            if line.startswith('@A'):
                line = find_between(line, "@", "1:N:")
                with open(outputfastq, 'a') as newfile:
                    newfile.write("@" + line + "\n")
                    newfile.write(next(fh))
                    newfile.write(next(fh))
                    newfile.write(next(fh))

if __name__ == '__main__':
    if len(sys.argv) == 3:
        editheader(sys.argv[1], sys.argv[2])
    else:
        print("Usage: editfastqheaders.py input.fastq output.fastq ")
        sys.exit(0)
